[package]
name = "shio_macros"
version = "0.1.0"
authors = ["Quentin Laveau <qlaveau@gmail.com>"]
workspace = ".."

[dependencies]
syn = { version="0.11.11", features=["full","parsing","printing"] }
quote="0.3"

[lib]
proc-macro = true

